	tilepal 0, GRAY, BROWN, BROWN, GRAY, BROWN, BROWN, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, BROWN, WATER, GREEN
	tilepal 0, GREEN, WATER, BROWN, BROWN, BROWN, GREEN, WATER, GREEN
	tilepal 0, GREEN, GREEN, GREEN, RED, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, RED, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY
