; INPUTS - Mon DVs in de, species in wGenderTemp
; OUTPUT - Mon's gender in wGenderTemp
GetMonGender::
	ld hl, MonGenderRatios
	ld a, [wGenderTemp]
	dec a
	ld c, a
	ld b, 0
	add hl, bc ; hl now points to the species gender ratio

; Attack DV
	ld a, [de]
	and $f0
	ld b, a
; Speed DV
	inc de
	ld a, [de]
	and $f0
	swap a
; Put them together
	or b
	ld b, a ; b now has the combined DVs

; Get the gender ratio
	ld a, [hl]

; Check for always one or another
	cp NO_GENDER
	jr z, .genderless

	cp FEMALE_ONLY
	jr z, .female

	and a ; MALE_ONLY
	jr z, .male

; Compare the ratio to the value we found earlier
	cp b
	jr c, .male

.female
	ld a, FEMALE
	jr .done
.male
	ld a, MALE
	jr .done
.genderless
	ld a, GENDERLESS
.done
	ld [wGenderTemp], a
	ret

MonGenderRatios:
	db SAME_BOTH_GENDERS ; RHYDON
	db FEMALE_ONLY       ; KANGASKHAN
	db MALE_ONLY         ; NIDORAN_M
	db FEMALE_75_PERCENT ; CLEFAIRY
	db SAME_BOTH_GENDERS ; SPEAROW
	db NO_GENDER         ; VOLTORB
	db MALE_ONLY         ; NIDOKING
	db SAME_BOTH_GENDERS ; SLOWBRO
	db MALE_88_PERCENT   ; IVYSAUR
	db SAME_BOTH_GENDERS ; EXEGGUTOR
	db SAME_BOTH_GENDERS ; LICKITUNG
	db SAME_BOTH_GENDERS ; EXEGGCUTE
	db SAME_BOTH_GENDERS ; GRIMER
	db SAME_BOTH_GENDERS ; GENGAR
	db FEMALE_ONLY       ; NIDORAN_F
	db FEMALE_ONLY       ; NIDOQUEEN
	db SAME_BOTH_GENDERS ; CUBONE
	db SAME_BOTH_GENDERS ; RHYHORN
	db SAME_BOTH_GENDERS ; LAPRAS
	db MALE_75_PERCENT   ; ARCANINE
	db NO_GENDER         ; MEW
	db SAME_BOTH_GENDERS ; GYARADOS
	db SAME_BOTH_GENDERS ; SHELLDER
	db SAME_BOTH_GENDERS ; TENTACOOL
	db SAME_BOTH_GENDERS ; GASTLY
	db SAME_BOTH_GENDERS ; SCYTHER
	db NO_GENDER         ; STARYU
	db MALE_88_PERCENT   ; BLASTOISE
	db SAME_BOTH_GENDERS ; PINSIR
	db SAME_BOTH_GENDERS ; TANGELA
	db MALE_88_PERCENT   ; CHIKORITA
	db MALE_88_PERCENT   ; BAYLEEF
	db MALE_75_PERCENT   ; GROWLITHE
	db SAME_BOTH_GENDERS ; ONIX
	db SAME_BOTH_GENDERS ; FEAROW
	db SAME_BOTH_GENDERS ; PIDGEY
	db SAME_BOTH_GENDERS ; SLOWPOKE
	db MALE_75_PERCENT   ; KADABRA
	db SAME_BOTH_GENDERS ; GRAVELER
	db FEMALE_ONLY       ; CHANSEY
	db MALE_75_PERCENT   ; MACHOKE
	db NO_GENDER         ; MR_MIME
	db MALE_ONLY         ; HITMONLEE
	db MALE_ONLY         ; HITMONCHAN
	db SAME_BOTH_GENDERS ; ARBOK
	db SAME_BOTH_GENDERS ; PARASECT
	db SAME_BOTH_GENDERS ; PSYDUCK
	db SAME_BOTH_GENDERS ; DROWZEE
	db SAME_BOTH_GENDERS ; GOLEM
	db MALE_88_PERCENT   ; MEGANIUM
	db MALE_75_PERCENT   ; MAGMAR
	db MALE_88_PERCENT   ; CYNDAQUIL
	db MALE_75_PERCENT   ; ELECTABUZZ
	db NO_GENDER         ; MAGNETON
	db SAME_BOTH_GENDERS ; KOFFING
	db MALE_88_PERCENT   ; QUILAVA
	db SAME_BOTH_GENDERS ; MANKEY
	db SAME_BOTH_GENDERS ; SEEL
	db SAME_BOTH_GENDERS ; DIGLETT
	db MALE_ONLY         ; TAUROS
	db MALE_88_PERCENT   ; TYPHLOSION
	db MALE_88_PERCENT   ; TOTODILE
	db MALE_88_PERCENT   ; CROCONAW
	db NO_GENDER         ; FARFETCHD
	db SAME_BOTH_GENDERS ; VENONAT
	db SAME_BOTH_GENDERS ; DRAGONITE
	db MALE_88_PERCENT   ; FERALIGATR
	db SAME_BOTH_GENDERS ; SENTRET
	db SAME_BOTH_GENDERS ; FURRET
	db SAME_BOTH_GENDERS ; DODUO
	db SAME_BOTH_GENDERS ; POLIWAG
	db FEMALE_ONLY       ; JYNX
	db NO_GENDER         ; MOLTRES
	db NO_GENDER         ; ARTICUNO
	db NO_GENDER         ; ZAPDOS
	db NO_GENDER         ; DITTO
	db SAME_BOTH_GENDERS ; MEOWTH
	db SAME_BOTH_GENDERS ; KRABBY
	db SAME_BOTH_GENDERS ; HOOTHOOT
	db SAME_BOTH_GENDERS ; NOCTOWL
	db SAME_BOTH_GENDERS ; LEDYBA
	db FEMALE_75_PERCENT ; VULPIX
	db FEMALE_75_PERCENT ; NINETALES
	db SAME_BOTH_GENDERS ; PIKACHU
	db SAME_BOTH_GENDERS ; RAICHU
	db SAME_BOTH_GENDERS ; LEDIAN
	db SAME_BOTH_GENDERS ; SPINARAK
	db SAME_BOTH_GENDERS ; DRATINI
	db SAME_BOTH_GENDERS ; DRAGONAIR
	db MALE_88_PERCENT   ; KABUTO
	db MALE_88_PERCENT   ; KABUTOPS
	db SAME_BOTH_GENDERS ; HORSEA
	db SAME_BOTH_GENDERS ; SEADRA
	db SAME_BOTH_GENDERS ; ARIADOS
	db SAME_BOTH_GENDERS ; CROBAT
	db SAME_BOTH_GENDERS ; SANDSHREW
	db SAME_BOTH_GENDERS ; SANDSLASH
	db MALE_88_PERCENT   ; OMANYTE
	db MALE_88_PERCENT   ; OMASTAR
	db FEMALE_75_PERCENT ; JIGGLYPUFF
	db FEMALE_75_PERCENT ; WIGGLYTUFF
	db MALE_88_PERCENT   ; EEVEE
	db MALE_88_PERCENT   ; FLAREON
	db MALE_88_PERCENT   ; JOLTEON
	db MALE_88_PERCENT   ; VAPOREON
	db MALE_75_PERCENT   ; MACHOP
	db SAME_BOTH_GENDERS ; ZUBAT
	db SAME_BOTH_GENDERS ; EKANS
	db SAME_BOTH_GENDERS ; PARAS
	db SAME_BOTH_GENDERS ; POLIWHIRL
	db SAME_BOTH_GENDERS ; POLIWRATH
	db SAME_BOTH_GENDERS ; WEEDLE
	db SAME_BOTH_GENDERS ; KAKUNA
	db SAME_BOTH_GENDERS ; BEEDRILL
	db SAME_BOTH_GENDERS ; CHINCHOU
	db SAME_BOTH_GENDERS ; DODRIO
	db SAME_BOTH_GENDERS ; PRIMEAPE
	db SAME_BOTH_GENDERS ; DUGTRIO
	db SAME_BOTH_GENDERS ; VENOMOTH
	db SAME_BOTH_GENDERS ; DEWGONG
	db SAME_BOTH_GENDERS ; LANTURN
	db SAME_BOTH_GENDERS ; PICHU
	db SAME_BOTH_GENDERS ; CATERPIE
	db SAME_BOTH_GENDERS ; METAPOD
	db SAME_BOTH_GENDERS ; BUTTERFREE
	db MALE_75_PERCENT   ; MACHAMP
	db FEMALE_75_PERCENT ; CLEFFA
	db SAME_BOTH_GENDERS ; GOLDUCK
	db SAME_BOTH_GENDERS ; HYPNO
	db SAME_BOTH_GENDERS ; GOLBAT
	db NO_GENDER         ; MEWTWO
	db MALE_88_PERCENT   ; SNORLAX
	db SAME_BOTH_GENDERS ; MAGIKARP
	db FEMALE_75_PERCENT ; IGGLYBUFF
	db MALE_88_PERCENT   ; TOGEPI
	db SAME_BOTH_GENDERS ; MUK
	db MALE_88_PERCENT   ; TOGETIC
	db SAME_BOTH_GENDERS ; KINGLER
	db SAME_BOTH_GENDERS ; CLOYSTER
	db SAME_BOTH_GENDERS ; NATU
	db NO_GENDER         ; ELECTRODE
	db FEMALE_75_PERCENT ; CLEFABLE
	db SAME_BOTH_GENDERS ; WEEZING
	db SAME_BOTH_GENDERS ; PERSIAN
	db SAME_BOTH_GENDERS ; MAROWAK
	db SAME_BOTH_GENDERS ; XATU
	db SAME_BOTH_GENDERS ; HAUNTER
	db MALE_75_PERCENT   ; ABRA
	db MALE_75_PERCENT   ; ALAKAZAM
	db SAME_BOTH_GENDERS ; PIDGEOTTO
	db SAME_BOTH_GENDERS ; PIDGEOT
	db NO_GENDER         ; STARMIE
	db MALE_88_PERCENT   ; BULBASAUR
	db MALE_88_PERCENT   ; VENUSAUR
	db SAME_BOTH_GENDERS ; TENTACRUEL
	db SAME_BOTH_GENDERS ; MAREEP
	db SAME_BOTH_GENDERS ; GOLDEEN
	db SAME_BOTH_GENDERS ; SEAKING
	db SAME_BOTH_GENDERS ; FLAAFFY
	db SAME_BOTH_GENDERS ; AMPHAROS
	db SAME_BOTH_GENDERS ; BELLOSSOM
	db SAME_BOTH_GENDERS ; MARILL
	db SAME_BOTH_GENDERS ; PONYTA
	db SAME_BOTH_GENDERS ; RAPIDASH
	db SAME_BOTH_GENDERS ; RATTATA
	db SAME_BOTH_GENDERS ; RATICATE
	db MALE_ONLY         ; NIDORINO
	db FEMALE_ONLY       ; NIDORINA
	db SAME_BOTH_GENDERS ; GEODUDE
	db NO_GENDER         ; PORYGON
	db MALE_88_PERCENT   ; AERODACTYL
	db SAME_BOTH_GENDERS ; AZUMARILL
	db NO_GENDER         ; MAGNEMITE
	db SAME_BOTH_GENDERS ; SUDOWOODO
	db SAME_BOTH_GENDERS ; POLITOED
	db MALE_88_PERCENT   ; CHARMANDER
	db MALE_88_PERCENT   ; SQUIRTLE
	db MALE_88_PERCENT   ; CHARMELEON
	db MALE_88_PERCENT   ; WARTORTLE
	db MALE_88_PERCENT   ; CHARIZARD
	db SAME_BOTH_GENDERS ; HOPPIP
	db NO_GENDER         ; FOSSIL_KABUTOPS
	db NO_GENDER         ; FOSSIL_AERODACTYL
	db NO_GENDER         ; MON_GHOST
	db SAME_BOTH_GENDERS ; ODDISH
	db SAME_BOTH_GENDERS ; GLOOM
	db SAME_BOTH_GENDERS ; VILEPLUME
	db SAME_BOTH_GENDERS ; BELLSPROUT
	db SAME_BOTH_GENDERS ; WEEPINBELL
	db SAME_BOTH_GENDERS ; VICTREEBEL
	db SAME_BOTH_GENDERS ; SKIPLOOM
	db SAME_BOTH_GENDERS ; JUMPLUFF
	db SAME_BOTH_GENDERS ; AIPOM
	db SAME_BOTH_GENDERS ; SUNKERN
	db SAME_BOTH_GENDERS ; SUNFLORA
	db SAME_BOTH_GENDERS ; YANMA
	db SAME_BOTH_GENDERS ; WOOPER
	db SAME_BOTH_GENDERS ; QUAGSIRE
	db MALE_88_PERCENT   ; ESPEON
	db MALE_88_PERCENT   ; UMBREON
	db SAME_BOTH_GENDERS ; MURKROW
	db SAME_BOTH_GENDERS ; SLOWKING
	db SAME_BOTH_GENDERS ; MISDREAVUS
	db NO_GENDER         ; UNOWN
	db SAME_BOTH_GENDERS ; WOBBUFFET
	db SAME_BOTH_GENDERS ; GIRAFARIG
	db SAME_BOTH_GENDERS ; PINECO
	db SAME_BOTH_GENDERS ; FORRETRESS
	db SAME_BOTH_GENDERS ; DUNSPARCE
	db SAME_BOTH_GENDERS ; GLIGAR
	db SAME_BOTH_GENDERS ; STEELIX
	db FEMALE_75_PERCENT ; SNUBBULL
	db FEMALE_75_PERCENT ; GRANBULL
	db SAME_BOTH_GENDERS ; QWILFISH
	db SAME_BOTH_GENDERS ; SCIZOR
	db SAME_BOTH_GENDERS ; SHUCKLE
	db SAME_BOTH_GENDERS ; HERACROSS
	db SAME_BOTH_GENDERS ; SNEASEL
	db SAME_BOTH_GENDERS ; TEDDIURSA
	db SAME_BOTH_GENDERS ; URSARING
	db SAME_BOTH_GENDERS ; SLUGMA
	db SAME_BOTH_GENDERS ; MAGCARGO
	db SAME_BOTH_GENDERS ; SWINUB
	db SAME_BOTH_GENDERS ; PILOSWINE
	db FEMALE_75_PERCENT ; CORSOLA
	db SAME_BOTH_GENDERS ; REMORAID
	db SAME_BOTH_GENDERS ; OCTILLERY
	db SAME_BOTH_GENDERS ; DELIBIRD
	db SAME_BOTH_GENDERS ; MANTINE
	db SAME_BOTH_GENDERS ; SKARMORY
	db SAME_BOTH_GENDERS ; HOUNDOUR
	db SAME_BOTH_GENDERS ; HOUNDOOM
	db SAME_BOTH_GENDERS ; KINGDRA
	db SAME_BOTH_GENDERS ; PHANPY
	db SAME_BOTH_GENDERS ; DONPHAN
	db NO_GENDER         ; PORYGON2
	db SAME_BOTH_GENDERS ; STANTLER
	db SAME_BOTH_GENDERS ; SMEARGLE
	db MALE_ONLY         ; TYROGUE
	db MALE_ONLY         ; HITMONTOP
	db FEMALE_ONLY       ; SMOOCHUM
	db MALE_75_PERCENT   ; ELEKID
	db MALE_75_PERCENT   ; MAGBY
    db FEMALE_ONLY       ; MILTANK
    db FEMALE_ONLY       ; BLISSEY
    db NO_GENDER         ; RAIKOU
    db NO_GENDER         ; ENTEI
    db NO_GENDER         ; SUICUNE
    db SAME_BOTH_GENDERS ; LARVITAR
    db SAME_BOTH_GENDERS ; PUPITAR
    db SAME_BOTH_GENDERS ; TYRANITAR
    db NO_GENDER         ; LUGIA
    db NO_GENDER         ; HOOH
    db NO_GENDER         ; CELEBI
